---
title: "adb_key_indicators"
author: "Vincent Pontines"
date: "2025-08-28"
output: html_document                        
---

```{r setup, include=FALSE}
library(here)
library(DT)                         
library(janitor)
library(tidyverse)
library(data.table)
library(DataExplorer)
library(skimr)
source(here("templates/import_helper.R"))
source(here("templates/summary_helper.R"))
```



# Load dataset
```{r}
# Load here if you want project-relative paths
# library(here)

# Full path relative to project root
file_path <- here("data", "raw", "adb_key_indicators", 
    "KIDB-export-7114db13-e5a3-4a5d-99ea-3deb0a4a8e31.csv")

# Import the CSV
df <- fread(file_path)
```

```{r}
dim(df)
```

# Data Glimpse
```{r}
glimpse(df)
```

# 
```{r}
# Pivot from wide to long format
df_long <- df %>%
  pivot_longer(
    cols = `2000`:`2025`, 
    names_to = "Year", 
    values_to = "Value"
  ) %>%
  # Convert Year to numeric and filter out missing values
  mutate(Year = as.numeric(Year)) %>%
  filter(!is.na(Value))

# Inspect the tidied data
head(df_long)
```

# Reports
```{r}
# datatable(head(df, 1000))   # only first 1000 rows
create_report(df)
```

# Summary statistics
```{r}
library(here)
str(df)

summarize_numeric(df)
```


# 